Sum function implemented
js-tasks-ru/nodejs-20220303_krav4enkodm pull request #1
Opened 2022-03-15 18:38 UTC by krav4enkodm

2022-03-15 18:38 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @tadjik1 должен запустить тесты.

2022-03-17 16:21 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-03-20 15:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-03-20 15:10 UTC, tadjik1 requested changes
Отметил момент, который необходимо поправить. Остальные задачи выполнены отлично 👍

2022-03-20 15:10 UTC, tadjik1 commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +    this._body.push(chunk);
Вы таким образом будете в памяти держать все данные передаваемые, это может привести к проблемам. Правильнее будет хранить лишь размер передаваемых данных, а не сами данные.

2022-09-16 15:50 UTC, closed without merging